/** Light Aluminium Sheet theme: the deterministic ingot story sits on a bright metal work surface with soft grounded shadows. */
// Design note: bright, cool studio lighting that makes the animated aluminium stack read as silver.
import { Canvas, useFrame, useThree } from "@react-three/fiber";
import { ContactShadows } from "@react-three/drei";
import * as THREE from "three";
import { Ingot } from "./Ingot";
import { GROUND_Y, STACK_ITEMS } from "./stacking";

function Pallet(){return <group><mesh position={[0,-.08,0]} castShadow receiveShadow><boxGeometry args={[8.72,.16,3.28]} /><meshStandardMaterial color="#bdc9c8" metalness={.45} roughness={.56} /></mesh>{[-1.25,0,1.25].map(z=><mesh key={z} position={[0,-.18,z]} castShadow receiveShadow><boxGeometry args={[8.9,.16,.28]} /><meshStandardMaterial color="#aab9b8" metalness={.32} roughness={.7} /></mesh>)}{[-2.75,0,2.75].map(x=><mesh key={x} position={[x,-.37,0]} castShadow receiveShadow><boxGeometry args={[.38,.23,3.28]} /><meshStandardMaterial color="#a6b5b4" metalness={.3} roughness={.72} /></mesh>)}</group>;}
const clamp=(value:number)=>Math.min(1,Math.max(0,value)); const smooth=(value:number,start:number,end:number)=>{const t=clamp((value-start)/(end-start));return t*t*(3-2*t);}; const mix=(a:number,b:number,t:number)=>a+(b-a)*t;
function writePath(progress:number,points:[number,number,number][],out:THREE.Vector3){const segment=progress<.3?0:progress<.74?1:2;const limits=segment===0?[0,.3]:segment===1?[.3,.74]:[.74,1];const t=smooth(progress,limits[0],limits[1]);const a=points[segment],b=points[segment+1];out.set(mix(a[0],b[0],t),mix(a[1],b[1],t),mix(a[2],b[2],t));}
function CameraRig({progress}:{progress:React.MutableRefObject<number>}){const{camera,size}=useThree();const target=new THREE.Vector3();const positionPoints: [number,number,number][]=[[4.9,3.25,14.8],[3.5,2.45,11.6],[2.6,3,14],[4.9,3.25,14.8]];const mobilePoints:[number,number,number][]=[[3.8,2.55,15.9],[3.1,2.1,13.6],[2.55,2.55,15],[3.8,2.55,15.9]];const targetPoints:[number,number,number][]=[[0,.82,0],[0,.9,0],[0,1.35,-1.15],[0,.82,0]];useFrame(()=>{writePath(progress.current,size.width<640?mobilePoints:positionPoints,camera.position);writePath(progress.current,targetPoints,target);camera.lookAt(target);});return null;}

export function IngotScene({progress}:{progress:React.MutableRefObject<number>}){const mobile=typeof window!=="undefined"&&window.innerWidth<640;const sceneItems=mobile?STACK_ITEMS.filter(item=>item.layer<2||(item.layer===2&&item.column===1)):STACK_ITEMS;return <div className="ingot-canvas" aria-hidden="true"><Canvas shadows dpr={mobile?[1,1.1]:[1,1.2]} camera={{fov:29,position:[4.9,3.25,14.8]}} gl={{antialias:true,alpha:true,powerPreference:"high-performance"}} onCreated={({gl})=>{gl.shadowMap.enabled=true;gl.shadowMap.type=THREE.PCFSoftShadowMap;}}><color attach="background" args={["#edf4f3"]} /><fog attach="fog" args={["#edf4f3",11,22]} /><hemisphereLight args={["#ffffff","#c6d2d4",1.7]} /><directionalLight castShadow position={[-4.4,7.8,5.8]} intensity={4.1} color="#ffffff" shadow-mapSize={[1024,1024]} shadow-bias={-.00015} /><spotLight position={[4.3,5.3,2.8]} intensity={7.8} angle={.52} penumbra={.92} color="#f4fbff" /><pointLight position={[-3.5,1.1,2.8]} intensity={1.7} distance={9} color="#dbeeff" /><Pallet />{sceneItems.map(item=><Ingot key={item.id} item={item} progress={progress} />)}<mesh rotation={[-Math.PI/2,0,0]} position={[0,GROUND_Y-.39,0]} receiveShadow><planeGeometry args={[30,30]} /><meshStandardMaterial color="#e9f0ee" roughness={.92} metalness={.08} /></mesh><ContactShadows position={[0,GROUND_Y-.385,0]} opacity={.2} scale={14} blur={2.4} far={6} resolution={256} color="#536365" /><CameraRig progress={progress} /></Canvas></div>;}
